feeds:
  - url: https://galaxyproject.org/eu/feed.atom

    format: "📝 New blog post Released!\n{link}\n\n{content}"

    media:
      - - mastodon-eu-freiburg
        - matrix-eu-announce
        - linkedin-galaxyproject
      - - bluesky-galaxyproject

    mentions:
      mastodon-eu-freiburg:
        - galaxyproject@mstdn.science
      bluesky-galaxyproject:
        - galaxyproject.bsky.social

    hashtags:
      mastodon-eu-freiburg:
        - UseGalaxy
        - GalaxyProject
        - UniFreiburg
        - EOSC
        - EuroScienceGateway
      bluesky-galaxyproject:
        - UseGalaxy
        - GalaxyProject
        - UniFreiburg
        - EOSC
        - EuroScienceGateway
      linkedin-galaxyproject:
        - UseGalaxy
        - GalaxyProject
        - UniFreiburg
        - EOSC
        - EuroScienceGateway

# youtube_channels:
#   - channel: "https://www.youtube.com/c/galaxyproject"
#     format: "🎥 New YouTube Video Released!\n\n{title}\n\n🔗 Watch it now: {link}"


# citations:
#   - zotero_group_id: 1732893
#     tag: ">UseGalaxy.eu || >RNA Workbench || RNA workbench || >ASaiM || >Live EU || >Proteomics EU || >Metagenomics EU || >ML Workbench || >ChemicalToolbox"
#     format: "📰 New publication Released!\n\n{title}\nBy: {creators}\n{url}"
